/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotopicos;

import java.awt.Desktop;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author HP OMEN
 */
public class JFrameEjecutar extends javax.swing.JFrame {
    JFrameMenu menuPrin = null;
    String rutaArchivoPDF;
    
    
    /**
     * Creates new form JFrameEjecutar
     */
    public JFrameEjecutar(JFrameMenu menu) {
         menuPrin = menu;  // Obtenemos la instancia del MenuPrincipal
         initComponents();
         this.setTitle("Ejecutor");
         this.setLocationRelativeTo(null); //Hace que el Frame aparezca al centro
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);     
         jCombOpcion.addItem("...");
         jCombOpcion.addItem("Selecionar otro");
         jCombOpcion.addItem("RegistroAlumno");
         jCombOpcion.addItem("App de salud");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jButEjecutar = new javax.swing.JButton();
        jButLimpiar = new javax.swing.JButton();
        jButRegresar = new javax.swing.JButton();
        jCombOpcion = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButEjecutar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButEjecutar.setText("Ejecutar");
        jButEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjecutarActionPerformed(evt);
            }
        });

        jButLimpiar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButLimpiar.setText("Limpiar");
        jButLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButLimpiarActionPerformed(evt);
            }
        });

        jButRegresar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jCombOpcion.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jCombOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombOpcionActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCombOpcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jCombOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjecutarActionPerformed
        int seleccion = jCombOpcion.getSelectedIndex(); //obtiene el indice del comboBox
        try {
            if(seleccion == 0){
                    JOptionPane.showMessageDialog(null, "Seleccione una Aplicación válida...");
                    return;
            }else if(seleccion == 1){
                 JFileChooser chooser = new  JFileChooser();
                 int x = chooser.showOpenDialog(this);
                 
                 if( x == JFileChooser.APPROVE_OPTION){
                      File f = chooser.getSelectedFile();
                      Desktop.getDesktop().open(f);
//                      try {
//                         Runtime.getRuntime().exec("cmd /c start"+ f.getAbsolutePath());
//                     } catch (Exception e) {
//                         e.printStackTrace();
//                     }
                      
                 }
        
            }else if (seleccion == 2){
                try{
                    Runtime.getRuntime().exec("java -jar ./RegistroAlumnos.jar");
                    //El parametro ./ es para que busque en la carpeta raiz, es decir siempre buscara en donde este el jar compilado       
                    } catch(IOException e){
                       JOptionPane.showMessageDialog(null, "No fué posible abrir la Aplicación.");
                    }
                    return ;
            }else if (seleccion == 3) {
                try{
                    Runtime.getRuntime().exec("java -jar ./Opcion_c.jar");
                    //El parametro ./ es para que busque en la carpeta raiz, es decir siempre buscara en donde este el jar compilado       
                    } catch(IOException e){
                       JOptionPane.showMessageDialog(null, "No fué posible abrir la Aplicación.");
                    }
                    return;
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButEjecutarActionPerformed

    private void jButLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButLimpiarActionPerformed
       jCombOpcion.setSelectedIndex(0);
    }//GEN-LAST:event_jButLimpiarActionPerformed

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        menuPrin.toFront();
        this.dispose();   //Cierra la ventana
    }//GEN-LAST:event_jButRegresarActionPerformed
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //Este Metodo se Ejecuta al cerrar una ventana, como formWindowOpened
        menuPrin.toFront();   //Regresa al frente al menu Principal   
    }//GEN-LAST:event_formWindowClosed

    private void jCombOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombOpcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new JFrameEjecutar().setVisible(true);
            }
        });
        
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButEjecutar;
    private javax.swing.JButton jButLimpiar;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JComboBox<String> jCombOpcion;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
