/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotopicos;


import java.awt.Desktop;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Jose Angel
 */
public class JFrameMenu extends javax.swing.JFrame {
    public static JFrameEjecutar ejecuta = null;
     JFileChooser choose; 
     String rutaArchivoPDF;
    
    /**
     * Creates new form JFrameMenu
     */
    public JFrameMenu() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Aplicación TADP");
        this.setLocationRelativeTo(null);//Abrir Frame en el centro de la pantalla        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarra = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuImprimir = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenuAplicacion = new javax.swing.JMenu();
        jMenuEjecutor = new javax.swing.JMenuItem();
        jMenuOpcionB = new javax.swing.JMenuItem();
        jMenuOpcionC = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuManual = new javax.swing.JMenuItem();
        JMenuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion TADP");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(70, 70));
        setPreferredSize(new java.awt.Dimension(480, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giphy.gif"))); // NOI18N
        jLabel2.setText("Bienvenido");
        jLabel2.setAlignmentY(10.0F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 460, 300));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jMenuBarra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuBarraFocusGained(evt);
            }
        });

        jMenuArchivo.setText("Archivo");
        jMenuArchivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuArchivoFocusGained(evt);
            }
        });
        jMenuArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuArchivoMouseExited(evt);
            }
        });

        jMenuImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print-icon.png"))); // NOI18N
        jMenuImprimir.setText("Imprimir");
        jMenuImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImprimirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuImprimir);

        jMenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Users-Exit-icon.png"))); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuSalir);

        jMenuBarra.add(jMenuArchivo);

        jMenuAplicacion.setText("Aplicación");
        jMenuAplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuAplicacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuAplicacionMouseExited(evt);
            }
        });

        jMenuEjecutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eject-icon.png"))); // NOI18N
        jMenuEjecutor.setText("Ejecutor");
        jMenuEjecutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEjecutorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuEjecutorMousePressed(evt);
            }
        });
        jMenuEjecutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEjecutorActionPerformed(evt);
            }
        });
        jMenuAplicacion.add(jMenuEjecutor);

        jMenuOpcionB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manual2.png"))); // NOI18N
        jMenuOpcionB.setText("Registro de alumnos");
        jMenuOpcionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpcionBActionPerformed(evt);
            }
        });
        jMenuAplicacion.add(jMenuOpcionB);

        jMenuOpcionC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weight-Lift-icon.png"))); // NOI18N
        jMenuOpcionC.setText("App de salud");
        jMenuOpcionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpcionCActionPerformed(evt);
            }
        });
        jMenuAplicacion.add(jMenuOpcionC);

        jMenuBarra.add(jMenuAplicacion);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuAyudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuAyudaMouseExited(evt);
            }
        });

        jMenuManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/books-icon.png"))); // NOI18N
        jMenuManual.setText("Manual");
        jMenuManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuManualMouseEntered(evt);
            }
        });
        jMenuManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManualActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuManual);

        JMenuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        JMenuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about.png"))); // NOI18N
        JMenuAcercaDe.setText("Acerca de");
        JMenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(JMenuAcercaDe);

        jMenuBarra.add(jMenuAyuda);

        setJMenuBar(jMenuBarra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //HotKey Para el Ejecutor Ctrl+1
        jMenuEjecutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke 
        (java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        
        //HotKey Para el Opcion B Ctrl+2
        jMenuOpcionB.setAccelerator(javax.swing.KeyStroke.getKeyStroke 
        (java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        
        //HotKey Para el Opcion C Ctrl+3
        jMenuOpcionC.setAccelerator(javax.swing.KeyStroke.getKeyStroke 
        (java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        
      
         // HotKey Para Imprimir Ctrl+P
         jMenuImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke
        (java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
       
       //HotKey Para Manual Ctrl+M
        jMenuManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke 
       (java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
       
        //HotKey Para Acerca de Ctrl+A
        JMenuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke 
        (java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        
    }//GEN-LAST:event_formWindowOpened

    private void JMenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuAcercaDeActionPerformed
        new JFrameAcercaDe().setVisible(true);//Abrir frame acerca de
    }//GEN-LAST:event_JMenuAcercaDeActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        this.dispose();//Cerrar la ventana actual
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuArchivoMouseEntered
        jMenuArchivo.setPopupMenuVisible(true); //Abrir al pasar mouse por encima
    }//GEN-LAST:event_jMenuArchivoMouseEntered

    private void jMenuArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuArchivoMouseExited
              
    }//GEN-LAST:event_jMenuArchivoMouseExited

    private void jMenuBarraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBarraFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBarraFocusGained

    private void jMenuArchivoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuArchivoFocusGained
        
    }//GEN-LAST:event_jMenuArchivoFocusGained

    private void jMenuEjecutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEjecutorMouseClicked
       // JFrameEjecutar ejecuta = new JFrameEjecutar();  
    }//GEN-LAST:event_jMenuEjecutorMouseClicked

    private void jMenuEjecutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEjecutorMousePressed

    }//GEN-LAST:event_jMenuEjecutorMousePressed

    private void jMenuEjecutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEjecutorActionPerformed
        
        try {
            if (ejecuta == null) {  //Si no hay instancias de este Frame abiertas
                ejecuta = new JFrameEjecutar(this);   //Se instancia el Frame
                ejecuta.setVisible(true);   //Se hace visible
                this.toBack();  //Este frame se manda a background
            }else{
                ejecuta.setVisible(true); //Si ya hay una instancia abierta, solo se trae al frente.
                ejecuta.toFront();
                this.toBack();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    /*  ESTE CODIGO HACE LO MISMO QUE EL ANTERIOR BLOQUE CON LA DIFERENCIA DE QUE
        EVITA LA CREACION DE OTRA INSTANCIA Y MANDA MENSAJE DE ERROR
        if (instancia == false) {
            ejecuta = new JFrameEjecutar();
            ejecuta.setVisible(true);   //Abre la ventana de la clase JFrameEjecutar 
            this.toBack(); //Manda hacia atras a esta ventana
        }else{
            JOptionPane.showMessageDialog(null, "Otra instancia de esta ventana esta siendo ejecutada."
                    + "\nCierrela y vuelva a intentarlo...","Ya se esta ejecutando", JOptionPane.WARNING_MESSAGE);
    */    
        
    }//GEN-LAST:event_jMenuEjecutorActionPerformed

    private void jMenuAplicacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAplicacionMouseEntered
        jMenuAplicacion.doClick();//Abrir opciones de menu aplicacion al pasar el mouse por encima
    }//GEN-LAST:event_jMenuAplicacionMouseEntered

    private void jMenuAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAyudaMouseEntered
        jMenuAyuda.doClick();//Abrir opciones de menu ayuda al pasar el mouse por encima
    }//GEN-LAST:event_jMenuAyudaMouseEntered

    private void jMenuAplicacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAplicacionMouseExited
      
    }//GEN-LAST:event_jMenuAplicacionMouseExited

    private void jMenuAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAyudaMouseExited
    
    }//GEN-LAST:event_jMenuAyudaMouseExited

    private void jMenuManualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuManualMouseEntered

    }//GEN-LAST:event_jMenuManualMouseEntered

    private void jMenuOpcionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpcionBActionPerformed
       
        try{
        Runtime.getRuntime().exec("java -jar ./RegistroAlumnos.jar");
        //El parametro ./ es para que busque en la carpeta raiz, es decir siempre buscara en donde este el jar compilado       
        } catch(IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuOpcionBActionPerformed

    private void jMenuOpcionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpcionCActionPerformed
        
       try{
        Runtime.getRuntime().exec("java -jar ./Opcion_c.jar");
        //El parametro ./ es para que busque en la carpeta raiz, es decir siempre buscara en donde este el jar compilado       
        } catch(IOException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jMenuOpcionCActionPerformed

    private void jMenuImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImprimirActionPerformed

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("jpg, png, txt, doc, docx, pdf", //Caratula
            "jpg","png", "txt", "doc", "docx", "pdf");   //Extensiones permitidas a elegir
  
        choose = new JFileChooser();
        choose.setFileFilter(filtro);   //Establece el filtro
        int ruta = choose.showOpenDialog(this);//Variable para checar ruta
        rutaArchivoPDF = "error";
        if(ruta == JFileChooser.APPROVE_OPTION){//Guardar ruta
            File r = choose.getSelectedFile();//Asignar al archivo la ruta del archivo a guardar
            imprimir(r.toString());
        }
    
    }//GEN-LAST:event_jMenuImprimirActionPerformed

    private void jMenuManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManualActionPerformed
        try {
            // TODO add your handling code here: Manual de usuario.pdf
            File file = new File ("./ManualUsuario.pdf");
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Error al abrir el archivo");
            Logger.getLogger(JFrameMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuManualActionPerformed
    
    public void imprimir(String ruta){
        PrinterJob job = PrinterJob.getPrinterJob();
        job.printDialog();//mostrar dialogo para escoger impresora
        String impresora=job.getPrintService().getName();//Guardar ruta de impresora
        
        
       java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
       java.io.File fichero = new java.io.File(ruta);
       if (desktop.isSupported(Desktop.Action.PRINT)){
            try {
              try{
                 Process pr = Runtime.getRuntime().exec("Rundll32 printui.dll,PrintUIEntry /y /n \""+impresora+"\"");
                  }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Error: "+ex);
                  }
            desktop.print(fichero);
           } catch (Exception e){
                    JOptionPane.showMessageDialog(null,"Error de clase Desktop");
                    e.printStackTrace();
                }
       }else{
          JOptionPane.showMessageDialog(null, "No existe una aplicación asociada al tipo de archivo");
        }
}  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JFrameMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(JFrameMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(JFrameMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(JFrameMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
                new JFrameMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuAcercaDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAplicacion;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBarra;
    private javax.swing.JMenuItem jMenuEjecutor;
    private javax.swing.JMenuItem jMenuImprimir;
    private javax.swing.JMenuItem jMenuManual;
    private javax.swing.JMenuItem jMenuOpcionB;
    private javax.swing.JMenuItem jMenuOpcionC;
    private javax.swing.JMenuItem jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
